schema_version: "v0.1.0"
automation:
  identifier: "entraid-add-user-group-onprem"  # Ejemplo: talos-day2-aws
  name: "Añadir usuario / s a un grupo gestionado en OnPrem"
  description: "Este automatismo permite añadir un usuario/s a un grupo (/SRE/ON-PREMISE/02_on-premise_ad-assignUsersToGroup)"
  engineering_team: "Alejandro Santacana Canton"
  engineering_team_contact:
    engineering_team_contact_email: "santale@3p.mapfre.com"
    engineering_team_contact_name: "Alejandro Santacana Canton"
  engineering_team_responsible:
    engineering_team_responsible_email: "rcruz2@mapfre.com"
    engineering_team_responsible_name: "Raul de la Cruz"
  repository:
    repository_url: "https://bitbucket.org/mapfre-cloud-services/on-premise-ad-assignuserstogroup/"
  updated_at: "2023-10-02"  # Fecha de la última actualización
  version: "1.0.0"
  tags:
    tech:
      - "ONPREM"
      - "EntraId"
    scope:
      - "IdentityManagement"
  executor:
    executor_type: "Jenkins"  # Ejemplos: API REST, Jenkins, etc.
    environments:
      - environment: "pro"
        details:
          api_endpoint: "https://cloud.pro.devops.mapfre.com/jenkins/job/SRE/job/ON-PREM/job/02_on-premise_ad-assignUsersToGroup/"
          api_http_method: ""
          api_swagger_url: ""
          api_valid_response_codes:
            - 200
            - 201
          input_params:
            - name: "Peticion_Request"
              description: "en este campo se deberá incluir el ID de referencia de quién solicita ejecutar este autom, por ejemplo Si la ejecución es desde POSEIDON debera de contener el id_poseidon"
              type: "string"
              required: true
            - name: "Group_Name"
              description: "Este campo debera de ser el nombre del grupo"
              type: "string"
              required: true
            - name: "UserPrincipalName"
              description: "En este campo se deberá incluir los upn de los usuarios, si desea más de uno separe los upn's por comas"
              type: "string"
              required: true
            - name: "User_State"
              description: "En este campo se deberá de incluir el estado del usuario, solo permite dos valores present - absent. Este campo es Mandatory"
              type: "string"
              required: true
            - name: "operator"
              description: "En este campo se deberá de añadir el operador con el cual quedarán registradas las operaciones en onprem"
              type: "string"
              required: true
          output_params:
            - name: "resultado"
              description: "Descripción del resultado esperado"
              type: "string"
              required: true
          output_values_description: "Tanto el autom como el Jenkinsfile asociado a su ejecución, envian un mensaje de correo electrónico a una cuenta de correo harcodeada en el código de la pipeline de Jenkins"
  securizacion_parametros_salida: ""
  alarmado: ""
  qa: ""
  documentation: "https://bitbucket.org/mapfre-cloud-services/on-premise-ad-assignuserstogroup/src/main/"
  metricas:
    - "Métrica1"
    - "Métrica2"
  compliance_%: 100
