#V0.1
#Requirements for integrate Automation Catalog with Poseidon

automation:
  identifier: "unified-template"
  name: "Template Unificada"
  description: "Template unificada"
  engineering_team: "Unified Team"
  engineering_team_contact:
    engineering_team_contact_email: "unified_team@mail.com"
    engineering_team_contact_name: "Unified Team"
  engineering_team_responsible:
    engineering_team_responsible_email: "unified_responsible@mail.com"
    engineering_team_responsible_name: "Unified Responsible"
  repository: 
    repository_url: "N/A"
  updated_at: "2024-08-01"
  version: "1.0.0"
  tags:
    tech:
      - "Ansible"
      - ".Net"
      - "C#"
      - "Azure"
      - "Github Actions"
      - "Jenkins"
    scope:
      - "Gestion de usuarios"
      - "Medusa"
      - "IaaS"
      - "AWS"
      - "EC2"
      - "Infoblox"
  executor:
    executor_type: "Mixed"
    environments:
      - dev:
          aap_instance: "aap-lab-onprem"
          aap_template_identifier: "434"
          api_endpoint: "https://medusa.azure.mapfre.net/group/{adgroup_identifier}/members"
          api_http_method: "PATCH"
          api_swagger_url: "https://mapfre-identity-api-pre.azurewebsites.net/swagger/index.html"
          api_valid_response_codes:
            - 204
            - 201
          github_owner: "mapfrecloudpoc"
          github_repo: "thalos-workflows"
          github_branch: "main"
          github_workflow_file_name: "ansible.yaml"
          jenkins_organization: cloud
          jenkins_pipeline_name: "SRE/ON-PREM/01_infoblox_network_reservation/develop"
          jenkins_pipeline_url: "/job/SRE/job/ON-PREM/job/01_infoblox_network_reservation/job/develop/"
          input_params:
            - name: "extra_vars"
              description: "Objecto con los parametros del job"
              type: object
              required: true
              keys:
                - name: "Poseidon_job_id"
                  description: "Identificador de la peticion en Poseidon"
                  type: "string"
                  required: true              
                - name: "Poseidon_user_name"
                  description: "UPN del usuario peticionario"
                  type: string
                  required: true
                - name: "Poseidon_job_template_name"
                  description: "Nombre del flujo en Poseidon ejecutado"
                  type: string
                  required: true              
                - name: "Tenant"
                  description: "Nombre del tenant sobre el que crear el espacio de colaboracion"
                  type: string
                  required: true
                - name: "owner"
                  description: "UPN del usuario owner del espacio de colaboracion"
                  type: string
                  required: true              
                - name: "templateSPO"
                  description: "Nombre del template a utilizar"
                  type: string
                  required: true
            - name: "repository"
              description: "nombre del repositorio"
              type: string
              required: true              
              fixed_value: "mapfrecloudpoc/ansible-playbook-linuxvm-amazon23"
            - name: "ref"
              description: "rama"
              type: string
              required: true              
              fixed_value: "develop"
            - name: "environment"
              description: "Cloud Provider"
              type: string
              required: true              
              fixed_value: "AWS"
            - name: "ansiblevars"
              description: "Ansible Vars"
              type: object
              required: true
              keys:
                - name: "HOST"
                  description: "EC2 instance Identifier"
                  type: string
                  required: true
          output_params:
            - name: "available_networkaddress"
              description: "CIDR Reservado"
              type: string
              required: true
            - name: "networkaddr_reservation_comments"
              description: "Comentario apuntado en infoblox relativo a esta reserva"
              type: string
              required: false
          output_values_description: "Si devuelve un CIDR valido, es que se ha podido reservar. Si devuelve un 0, es que no hay IPs disponibles"
      - pre:
          aap_instance: "aap-lab-onprem"
          aap_template_identifier: "434"
          api_endpoint: "https://medusa.azure.mapfre.net/group/{adgroup_identifier}/members"
          api_http_method: "PATCH"
          api_swagger_url: "https://mapfre-identity-api-pre.azurewebsites.net/swagger/index.html"
          api_valid_response_codes:
            - 204
            - 201
          github_owner: "mapfrecloudpoc"
          github_repo: "thalos-workflows"
          github_branch: "main"
          github_workflow_file_name: "ansible.yaml"
          jenkins_organization: cloud
          jenkins_pipeline_name: "SRE/ON-PREM/01_infoblox_network_reservation/develop"
          jenkins_pipeline_url: "/job/SRE/job/ON-PREM/job/01_infoblox_network_reservation/job/develop/"
          input_params:
            - name: "extra_vars"
              description: "Objecto con los parametros del job"
              type: object
              required: true
              keys:
                - name: "Poseidon_job_id"
                  description: "Identificador de la peticion en Poseidon"
                  type: "string"
                  required: true              
                - name: "Poseidon_user_name"
                  description: "UPN del usuario peticionario"
                  type: string
                  required: true
                - name: "Poseidon_job_template_name"
                  description: "Nombre del flujo en Poseidon ejecutado"
                  type: string
                  required: true              
                - name: "Tenant"
                  description: "Nombre del tenant sobre el que crear el espacio de colaboracion"
                  type: string
                  required: true
                - name: "owner"
                  description: "UPN del usuario owner del espacio de colaboracion"
                  type: string
                  required: true              
                - name: "templateSPO"
                  description: "Nombre del template a utilizar"
                  type: string
                  required: true
            - name: "repository"
              description: "nombre del repositorio"
              type: string
              required: true              
              fixed_value: "mapfrecloudpoc/ansible-playbook-linuxvm-amazon23"
            - name: "ref"
              description: "rama"
              type: string
              required: true              
              fixed_value: "develop"
            - name: "environment"
              description: "Cloud Provider"
              type: string
              required: true              
              fixed_value: "AWS"
            - name: "ansiblevars"
              description: "Ansible Vars"
              type: object
              required: true
              keys:
                - name: "HOST"
                  description: "EC2 instance Identifier"
                  type: string
                  required: true
          output_params:
            - name: "available_networkaddress"
              description: "CIDR Reservado"
              type: string
              required: true
            - name: "networkaddr_reservation_comments"
              description: "Comentario apuntado en infoblox relativo a esta reserva"
              type: string
              required: false
          output_values_description: "Si devuelve un CIDR valido, es que se ha podido reservar. Si devuelve un 0, es que no hay IPs disponibles"
      - pro:
          aap_instance: "aap-pro-onprem"
          aap_template_identifier: "2039"
          api_endpoint: "https://medusa.azure.mapfre.net/group/{adgroup_identifier}/members"
          api_http_method: "PATCH"
          api_swagger_url: "https://mapfre-identity-api-pre.azurewebsites.net/swagger/index.html"
          api_valid_response_codes:
            - 204
            - 201
          github_owner: "mapfrecloudpoc"
          github_repo: "thalos-workflows-pro"
          github_branch: "main"
          github_workflow_file_name: "ansible.yaml"
          jenkins_organization: cloud
          jenkins_pipeline_name: "SRE/ON-PREM/01_infoblox_network_reservation/main"
          jenkins_pipeline_url: "/job/SRE/job/ON-PREM/job/01_infoblox_network_reservation/job/develop/"
          input_params:
            - name: "extra_vars"
              description: "Objecto con los parametros del job"
              type: object
              required: true
              keys:
                - name: "Poseidon_job_id"
                  description: "Identificador de la peticion en Poseidon"
                  type: "string"
                  required: true              
                - name: "Poseidon_user_name"
                  description: "UPN del usuario peticionario"
                  type: string
                  required: true
                - name: "Poseidon_job_template_name"
                  description: "Nombre del flujo en Poseidon ejecutado"
                  type: string
                  required: true              
                - name: "Tenant"
                  description: "Nombre del tenant sobre el que crear el espacio de colaboracion"
                  type: string
                  required: true
                - name: "owner"
                  description: "UPN del usuario owner del espacio de colaboracion"
                  type: string
                  required: true
  precons:
    - precon_name: "nombre de la precondicion a ejecutar. Obligatorio"
      precon_description: "descripcion de lo que trata la precondicion"
      condition: #opcional, serviria para que   pudiera incluir el paso de precondicion cuando se fuera a importar
        function_lambda_name: "nombre de la lambda a ejecutar"
        function_lambda_account: "cuenta de la lambda a ejecutar, si se trata de una ejecucion cross account"
        args": 
          - key: "nombre del parametro"
            value: "valor del parametro, de donde debe sacarlo"
        result_expected": 0 #resultado exitoso esperado por la precondicion
        error_message": "mensaje a ofrecer por el proceso en caso de error"